### ISSUE TITLE
"target/dist/bin/launch" path

### ISSUE THREAD

**Issue by tay45** [hacone/AgIn#2]
To analyze my modification csv file, I've installed the program. But, I don't understand what is the "target/dist/bin/launch" path in its command line ("target/dist/bin/launch -i path/to/modifications.csv -f path/to/reference.fasta -o output_prefix -b vector_specifier -g gamma -l min_length predict"). I can't find this path after installation. It seems that I have to generate something. Could you please let me know how I can handle it? Thank you!

**Comment by tay45** [comment]
I downloaded the 'AgIn-0.9' (https://github.com/hacone/AgIn/releases) instead of the installation ($ git clone git://github.com/hacone/AgIn.git AgIn), and I've found the "target/dist/bin/launch" path. 

But, I have an error such as "[AgIn$] ERROR: parseOpt: ill-formed arguments" when I run my command line ("/Users/xogur/AgIn-0.9/target/dist/bin/launch -i /Users/xogur/Desktop/modifications.csv -f /Users/xogur/Desktop/pDmeth.fa -o /Users/xogur/Desktop/AgIn -b P5C3_HdrR -g -0.88 -l 50"). Could you please let me know how I can fix this issue? Thank you!

**Comment by hacone** [comment]
Hi,

Sorry that the readme is a bit outdated.
In your command line, the task name should be specified (as the last
argument), so please try:
/Users/xogur/AgIn-0.9/target/dist/bin/launch -i
/Users/xogur/Desktop/modifications.csv
-f /Users/xogur/Desktop/pDmeth.fa -o /Users/xogur/Desktop/AgIn -b P5C3_HdrR
-g -0.88 -l 50 predict

Yuta

2016-06-16 10:03 GMT+09:00 xogur notifications@github.com:

**Comment by tay45** [comment]
Hi Yuta, 

Many thanks for your kind reply! 

I've run my command with the task name, but it just give me a .gff file without two of .wig files. And also, the gff file seems to be not complete. I am attaching my result at below. Thank you!

Taehyuk

---

Taehyuks-MacBook-Pro:~ Taehyuk$ /Users/Taehyuk/AgIn-0.9/target/dist/bin/launch -i /Users/Taehyuk/Desktop/modifications.csv -f /Users/Taehyuk/Desktop/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn/AgIn -b P5C3_HdrR -g -0.88 -l 50 predict

## [Tasks$] minlen, gamma = 50 -0.880000

constituent[0]: file:/Users/Taehyuk/AgIn-0.9/target/dist/lib/agin-1.0.jar
constituent[1]: file:/Users/Taehyuk/AgIn-0.9/target/dist/lib/opencsv-2.3.jar
constituent[2]: file:/Users/Taehyuk/AgIn-0.9/target/dist/lib/plexus-classworlds-2.4.jar
constituent[3]: file:/Users/Taehyuk/AgIn-0.9/target/dist/lib/scala-library.jar

## constituent[4]: file:/Users/Taehyuk/AgIn-0.9/target/dist/lib/xerial-core-3.2.2.jar

java.lang.NumberFormatException: For input string: "1.472"
    at java.lang.NumberFormatException.forInputString(NumberFormatException.java:65)
    at java.lang.Integer.parseInt(Integer.java:580)
    at java.lang.Integer.parseInt(Integer.java:615)
    at scala.collection.immutable.StringLike$class.toInt(StringLike.scala:229)
    at scala.collection.immutable.StringOps.toInt(StringOps.scala:31)
    at hacone.AgIn.IOManager$.hacone$AgIn$IOManager$$parseOne$1(IOManager.scala:112)
    at hacone.AgIn.IOManager$$anonfun$3.apply(IOManager.scala:120)
    at hacone.AgIn.IOManager$$anonfun$3.apply(IOManager.scala:120)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$1.next(Iterator.scala:853)
    at hacone.AgIn.IOManager$GroupIterator$Itr$1.next(IOManager.scala:95)
    at scala.collection.Iterator$$anon$1.next(Iterator.scala:853)
    at scala.collection.Iterator$$anon$1.head(Iterator.scala:840)
    at hacone.AgIn.IOManager$$anonfun$loadIPD$4.apply(IOManager.scala:125)
    at hacone.AgIn.IOManager$$anonfun$loadIPD$4.apply(IOManager.scala:124)
    at scala.collection.Iterator$$anon$11.next(Iterator.scala:328)
    at scala.collection.Iterator$$anon$14.hasNext(Iterator.scala:389)
    at scala.collection.Iterator$class.foreach(Iterator.scala:727)
    at scala.collection.AbstractIterator.foreach(Iterator.scala:1157)
    at hacone.AgIn.Tasks$.predict(Tasks.scala:192)
    at hacone.AgIn.AgIn$.main(AgIn.scala:722)
    at hacone.AgIn.AgIn.main(AgIn.scala)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:497)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launchStandard(Launcher.java:329)
    at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:239)
    at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:409)
    at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:352)
Taehyuks-MacBook-Pro:~ Taehyuk$ cd /Users/Taehyuk/Desktop/AgIn
Taehyuks-MacBook-Pro:AgIn Taehyuk$ ls
AgIn.gff
Taehyuks-MacBook-Pro:AgIn Taehyuk$

_The file contents in AgIn.gff
##gff-version 3
##date Wed Jun 15 22:13:46 PDT 2016
##feature-ontology http://song.cvs.sourceforge.net/_checkout*/song/ontology/sofa.obo?revision=1.12
##source AgIn 0.9
##source-commandline -i /Users/Taehyuk/Desktop/modifications.csv -f /Users/Taehyuk/Desktop/pDmeth.fa -o /Users/Taehyuk/Desktop/AgIn/AgIn -b P5C3_HdrR -g -0.88 -l 50 predict

**Comment by tay45** [comment]
Hi Yuta,

I understand what I made a wrong. I did run my analysis without the index file for FASTA file (.fai) in the same directory. Now, everything is fine. Thank you!

Taehyuk
